dbt_brooklyn:
  target: dev
  outputs:
    dev:
      account: "{{ env_var('SERVER') }}"
      database: "{{ env_var('DATABASE') }}"      
      role: "{{ env_var('ROLE') }}" 
      schema: "{{ env_var('SCHEMA_DEFAULT') }}" 
      threads: 4
      type: snowflake
      user: "{{ env_var('USER') }}"  
      password: "{{ env_var('PASSWORD') }}"  
      warehouse: "{{ env_var('WAREHOUSE') }}"  

    pro:
      account: "{{ env_var('SERVER') }}"
      database: "{{ env_var('DATABASE') }}"      
      role: "{{ env_var('ROLE') }}" 
      schema: "{{ env_var('SCHEMA_DEFAULT') }}" 
      threads: 4
      type: snowflake
      user: "{{ env_var('USER') }}"  
      password: "{{ env_var('PASSWORD') }}"  
      warehouse: "{{ env_var('WAREHOUSE') }}"     
    